# Generated by Django 4.1.3 on 2022-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='No Slug mentioned for this image', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.TextField(default='No tags were given to this image'),
            preserve_default=False,
        ),
    ]
