# Generated by Django 4.1.3 on 2022-11-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
